---
layout: post
title: "[java] TestNG에서 예외 테스트 작성하기"
description: " "
date: 2023-12-14
tags: [java]
comments: true
share: true
---

TestNG에서는 예외를 확인하는 테스트를 작성하는 방법을 제공합니다. 이를 통해 코드가 예상대로 예외를 발생시키는지 확인할 수 있습니다. 아래는 TestNG에서 예외를 테스트하는 방법에 대한 예시입니다.

## 예외를 발생시켜야 하는 메서드

```java
public class MyClass {
    public void methodThatThrowsException() throws CustomException {
        // 예외를 발생시키는 코드
        throw new CustomException("예외 발생!");
    }
}
```

## TestNG를 사용하여 예외 테스트 작성하기

```java
import org.testng.annotations.Test;

public class ExceptionTest {

    @Test(expectedExceptions = CustomException.class)
    public void testExceptionIsThrown() {
        MyClass myClass = new MyClass();
        myClass.methodThatThrowsException();
    }
}
```

위의 예시 코드에서 `@Test` 어노테이션의 `expectedExceptions` 속성을 사용하여 `CustomException`이 발생하는지 확인합니다. 이를 통해 `methodThatThrowsException` 메서드가 예상대로 예외를 발생시키는지 테스트할 수 있습니다.

이제 TestNG를 사용하여 예외를 테스트하는 방법에 대해 이해하셨습니다. 원하는 경우 실제 프로젝트에서 적용하여 효율적인 예외 처리를 보장할 수 있습니다.

더 많은 정보를 원하시면 TestNG 공식 문서를 참고해보세요!

[TestNG 공식 문서](https://testng.org/doc/documentation-main.html)